service: job-handler
runtime: python
threadsafe: no
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 86400

runtime_config:
  python_version: 3

resources:
  cpu: 1
  memory_gb: 4.0

handlers:
- url: /handle_job
  script: main.app
