service: job-handler
runtime: python
threadsafe: yes
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 86400

runtime_config:
  python_version: 3

handlers:
- url: /handle_job
  script: main.app
