service: task-handler
runtime: python
threadsafe: yes
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 86400

runtime_config:
  python_version: 3

automatic_scaling:
  max_num_instances: 1
  min_num_instances: 1

handlers:
- url: /handle_file
  script: main.app
