service: task-handler
runtime: python
threadsafe: yes
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3.6

manual_scaling:
  instances: 1

handlers:
- url: /handle_file
  script: main.app
